site_name: Vigiluxçš„ç¬”è®°æœ¬
site_url: https://vigilux418.github.io/notebook/
repo_url: https://github.com/vigilux418/notebook
repo_name: Vigilux's Notebook
edit_uri: edit/main/docs/
site_description: Vigiluxçš„ç¬”è®°æœ¬
nav:
  - ä¸»é¡µ:
        - index.md
  - è¯­è¨€: 
      - lang/index.md
      - Markdown: 
          - lang/Markdown/index.md
          - Markdownè¯­æ³•: lang/Markdown/grammar.md
      - LaTeX: 
          - lang/LaTeX/index.md
          - æ•°å­¦å…¬å¼åŸºç¡€: lang/LaTeX/math.md
      - YAML:
          - lang/YAML/index.md
          - YAMLåŸºç¡€: lang/YAML/grammar.md
  - è®¡ç®—æœº: 
        - cs/index.md
        - é«˜çº§æ•°æ®ç»“æž„ä¸Žç®—æ³•åˆ†æž: 
            - cs/ads/index.md
            - AVLæ ‘ã€Splayæ ‘ä¸Žæ‘Šè¿˜åˆ†æž: cs/ads/1.md
            - çº¢é»‘æ ‘ä¸ŽB+æ ‘: cs/ads/2.md
            - å€’æŽ’ç´¢å¼•: cs/ads/3.md
            - å·¦å¼å †ä¸Žæ–œå †: cs/ads/4.md
            - äºŒé¡¹å †: cs/ads/5.md
            - å›žæº¯æ³•: cs/ads/6.md
            - åˆ†æ²»æ³•: cs/ads/7.md
            - åŠ¨æ€è§„åˆ’: cs/ads/8.md
        - è®¡ç®—æœºç»„æˆ: 
            - cs/co/index.md
            - è®¡ç®—æœºæŠ½è±¡åŠç›¸å…³æŠ€æœ¯: cs/co/1.md
            - æŒ‡ä»¤ï¼šè®¡ç®—æœºçš„è¯­è¨€: cs/co/2.md
            - è®¡ç®—æœºçš„ç®—æœ¯è¿ç®—: cs/co/3.md
            - å¤„ç†å™¨: cs/co/4.md
  - ç”µæ°”:
        - ee/index.md
        - ç”µè·¯åŽŸç†: 
            - ee/cp/index.md
            - ç”µè·¯æ¦‚è¿°: ee/cp/1.md
            - ç”µè·¯åˆ†æžçš„åŸºæœ¬æ–¹æ³•åŠå®šç†: ee/cp/2.md
            - æ­£å¼¦äº¤æµç”µè·¯: ee/cp/3.md
            - è°æŒ¯ã€äº’æ„ŸåŠä¸‰ç›¸äº¤æµç”µè·¯: ee/cp/4.md
            - éžæ­£å¼¦å‘¨æœŸç”µè·¯åˆ†æž: ee/cp/5.md
            - è¿‡æ¸¡è¿‡ç¨‹çš„ç»å…¸è§£æ³•: ee/cp/6.md
  - é€šè¯†: 
        - general/index.md
        - å¤å˜å‡½æ•°ä¸Žç§¯åˆ†å˜æ¢: 
            - general/cf/index.md
            - å¤æ•°: general/cf/1.md
            - è§£æžå‡½æ•°: general/cf/2.md
            - å¤å˜å‡½æ•°çš„ç§¯åˆ†: general/cf/3.md
            - çº§æ•°: general/cf/4.md
            - ç•™æ•°: general/cf/5.md
            - ä¿è§’æ˜ å°„: general/cf/6.md
            - æ‹‰æ™®æ‹‰æ–¯å˜æ¢: general/cf/7.md
        - å¤§å­¦ç‰©ç†ï¼ˆç”²ï¼‰II: 
            - general/phy_2/index.md
            - çœŸç©ºä¸­çš„é™ç”µåœº: general/phy_2/1.md
            - é™ç”µåœºä¸­çš„å¯¼ä½“å’Œç”µä»‹è´¨: general/phy_2/2.md
            - ç¨³è¡¡ç”µæµ: general/phy_2/3.md
            - ç¨³æ’ç£åœº: general/phy_2/4.md
            - ç£åœºä¸­çš„ç£ä»‹è´¨: general/phy_2/5.md
            - ç”µç£æ„Ÿåº”: general/phy_2/6.md
            - ç”µç£åœºä¸Žç”µç£æ³¢: general/phy_2/7.md
  - å·¥å…·:
        - tools/index.md
        - MkDocs:  
            - tools/MkDocs/index.md
            - MkDocså»ºç«™æŒ‡å—: tools/MkDocs/1.md
            - Materialä¸»é¢˜è®¾ç½®: tools/MkDocs/2.md
            - Python Markdownå‚è€ƒ: tools/MkDocs/3.md
            - MkDocsç¾ŽåŒ–: tools/MkDocs/4.md
dev_addr: 127.0.0.1:8001
extra_css: 
    - stylesheets/extra.css
    - stylesheets/custom.css
    - stylesheets/status.css
    - https://gcore.jsdelivr.net/npm/lxgw-wenkai-screen-webfont@1.1.0/style.css
    - https://gcore.jsdelivr.net/npm/lxgw-wenkai-webfont@1.1.0/style.css
    - https://fonts.googleapis.com/css2?family=JetBrains+Mono:ital,wght@0,100..800;1,100..800&display=swap
extra_javascript: 
    - javascripts/mermaid.mjs
    - javascripts/mathjax.js
    - https://cdn.jsdelivr.net/gh/vigilux418/downloads@main/special_effects/lines.js
    - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
theme: 
    name: material
    custom_dir: overrides
    palette:
        # Palette toggle for light mode
        - media: "(prefers-color-scheme: light)"
          primary: custom
          scheme: default
          toggle: 
            icon: material/weather-sunny
            name: Switch to dark mode
        # Palette toggle for dark mode
        - media: "(prefers-color-scheme: dark)"
          primary: custom
          scheme: slate
          toggle: 
            icon: material/weather-night
            name: Switch to light mode
    font: false
    features:
        # - navigation.instant
        - navigation.instant.progress
        - navigation.tracking
        - navigation.tabs
        - navigation.tabs.sticky
        # - navigation.sections
        - navigation.expand
        - navigation.prune
        - navigation.indexes
        - toc.follow
        - navigation.top
        - search.highlight
        - search.share
        - search.suggest
        # - header.autohide
        - navigation.footer
        - content.action.edit
        - content.action.view
        - content.code.copy
        - content.code.annotate
        - content.tabs.link
        - content.tooltips
    language: zh
    icon: 
        logo: fontawesome/solid/book-atlas
        repo: fontawesome/brands/git-alt
        edit: material/file-edit
        view: material/file-eye
        admonition:
          note: octicons/tag-16
          abstract: octicons/checklist-16
          info: octicons/info-16
          tip: octicons/squirrel-16
          success: octicons/check-16
          question: octicons/question-16
          warning: octicons/alert-16
          failure: octicons/x-circle-16
          danger: octicons/zap-16
          bug: octicons/bug-16
          example: octicons/beaker-16
          quote: octicons/quote-16
        annotation: material/plus-circle
    favicon: images/favicon.png
markdown_extensions:
    - meta
    - toc:
        permalink: "âš“ï¸Ž"
    - abbr
    - pymdownx.highlight:
        anchor_linenums: true
        line_spans: __span
        pygments_lang_class: true
    - pymdownx.inlinehilite
    - pymdownx.snippets: 
        auto_append:
          - includes/abbreviations.md
    - admonition
    - pymdownx.details
    - pymdownx.superfences: 
        custom_fences: 
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
    - pymdownx.tabbed:
        alternate_style: true
        slugify: !!python/object/apply:pymdownx.slugs.slugify
          kwds:
            case: lower
    - attr_list
    - pymdownx.emoji:
        emoji_index: !!python/name:material.extensions.emoji.twemoji
        emoji_generator: !!python/name:material.extensions.emoji.to_svg
    - md_in_html
    - tables
    - footnotes
    - pymdownx.critic
    - pymdownx.caret
    - pymdownx.keys
    - pymdownx.mark
    - pymdownx.tilde
    - pymdownx.blocks.caption
    - def_list
    - pymdownx.tasklist: 
        custom_checkbox: true
    - pymdownx.arithmatex: 
        generic: true
    - pymdownx.betterem
    - pymdownx.smartsymbols
    - pymdownx.pathconverter: 
        base_path: '' # default: ''
        relative_path: '' # default ''
        absolute: false # default: false
        tags: 'a script img link object embed'
plugins:
    - macros: 
        # [[% raw %]]
        j2_block_start_string: '[[%'
        j2_block_end_string: '%]]'
        j2_variable_start_string: '[['
        j2_variable_end_string: ']]'
        # [[% endraw %]]   
    - meta
    - search: 
        lang:
            - en
            - zh
        separator: '[\s\u200b\-]'
    - git-revision-date-localized:
        type: datetime
        timezone: Asia/Shanghai
        locale: zh
        exclude: 
          - index.md
        fallback_to_build_date: true
        enable_creation_date: true
    - glightbox
    - statistics: 
        page_check_metadata: comments
    - encryptcontent:
        # https://github.com/unverbuggt/mkdocs-encryptcontent-plugin
        title_prefix: "ðŸ”’ "
        remember_password: True 
        decryption_failure_message: 'å¯†ç é”™è¯¯'
        encrypted_something:
          mkdocs-encrypted-toc: [nav, class]
extra:
    analytics: 
      provider: google
      property: G-GTK216Q9ET
      feedback:
        title: æ­¤é¡µé¢æœ‰å¸®åŠ©å—?
        ratings:
          - icon: material/emoticon-happy-outline
            name: å¸®åŠ©å¾ˆå¤§
            data: 1
            note: >-
              æ„Ÿè°¢ä½ çš„åé¦ˆ!
          - icon: material/emoticon-sad-outline
            name: äºŸå¾…æ”¹å–„
            data: 0
            note: >- 
              Thanks for your feedback! Help us improve this page by
              using our <a href="..." target="_blank" rel="noopener">feedback form</a>.
    social:
        - icon: fontawesome/brands/github
          link: https://github.com/vigilux418
        - icon: fontawesome/solid/home
          link: https://vigilux.top
        - icon: fontawesome/brands/docker
          link: https://app.docker.com/accounts/vigilux
        - icon: fontawesome/solid/paper-plane
          link: mailto:a3205767798@outlook.com
    scope: /
watch: 
    - includes
copyright: Copyright Â© 2025 Vigilux